options {
    directory "/var/cache/bind";
    recursion yes;
    allow-recursion { any; };        # intentionally open for labs 1 & 3
    allow-transfer { any; };         # intentionally open for lab 2
    dnssec-validation no;
    listen-on { any; };
};

zone "lab.local" {
    type master;
    file "/etc/bind/zones/lab.local.db";
};
